### ISSUE TITLE
vulkansdk Resource Not Found When Building and Running xr_hello_holoscan and volume_rendering_xr

### ISSUE THREAD

**Issue by codenML** [nvidia-holoscan/holohub#440]
```
 > [vulkansdk-builder 2/4] RUN wget -nv --show-progress --progress=bar:force:noscroll     https://sdk.lunarg.com/sdk/download/1.3.216.0/linux/vulkansdk-linux-x86_64-1.3.216.0.tar.gz:                                                          
0.681 https://sdk.lunarg.com/sdk/download/1.3.216.0/linux/vulkansdk-linux-x86_64-1.3.216.0.tar.gz:                                                              
0.682 2024-07-23 14:23:56 ERROR 404: Not Found.
```

**Steps to Reproduce**

1. Set up per [README](https://github.com/nvidia-holoscan/holohub/tree/main/applications/volume_rendering_xr#prerequisites)
2. Run either of the following commands in freshly cloned repo:
`./dev_container build_and_run xr_hello_holoscan`
`./dev_container build_and_run volume_rendering_xr`

[build_and_run_log.txt](https://github.com/user-attachments/files/16350365/build_and_run_log.txt)

**Comment by tbirdso** [comment]
Thanks for reporting @codenML . This issue shares a root cause with https://github.com/nvidia-holoscan/holoscan-sdk/issues/30 that was also identified today. I'll update the `volume_rendering_xr` Dockerfile with a similar resolution, and work with the Holoscan team to identify other potential failure points in HoloHub.
