### ISSUE TITLE
ImportError in Advanced Network Operator python

### ISSUE THREAD

**Issue by matin-karimpour** [nvidia-holoscan/holohub#449]
I'm trying to run the advanced network operator Python version but While attempting to execute the code, I encountered an ImportError that I am unable to resolve. It needs to be noted that the C++ version works for me. The specific error message is as follows: 

`ImportError: holohub/build/adv_networking_bench/python/lib/holohub/advanced_network_common/_advanced_network_common.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN8holoscan3ops21adv_net_free_all_pktsEPNS0_17AdvNetBurstParamsE`

I followed all instructions in advanced network operator docs and tried to run this in the DOCA container.
Could you please guide how to resolve this issue? If there are any specific steps or additional configurations required, I would greatly appreciate your assistance.

**Comment by matin-karimpour** [comment]
Thank you for your response. I have a few questions about the C++ version.

When I run the tx on one server and the rx on another, they can’t communicate with each other. However, when I send packets with ping to the rx, it can count them.

Can you explain why this is happening?

And another question that is related to the previous one, how can i build an application like basic network ping?

I really appreciate your help

**Comment by cliffburdick** [comment]
> Thank you for your response. I have a few questions about the C++ version.
> 
> When I run the tx on one server and the rx on another, they can’t communicate with each other. However, when I send packets with ping to the rx, it can count them.
> 
> Can you explain why this is happening?
> 
> And another question that is related to the previous one, how can i build an application like basic network ping?
> 
> I really appreciate your help

Hi @matin-karimpour, I'm not sure exactly what you're seeing without debugging it, but keep in mind that this application _does not_ implement basic networking functionality like ARP. If you're running the ANO sample by default the applications will not send ARP packets, nor will they respond to them. That's usually something the user implements, but we can add it in if that's useful. The reason it's not in there by default is some people either run it without a switch in between or they set a static ARP table. 

I'm not sure if that's what you're seeing, but you can look at the `ethtool -S` counters to get a better idea of what it's doing on both sides.

> And another question that is related to the previous one, how can i build an application like basic network ping?

The adv_networking_bench is similar to a ping, but just a very high rate. If you want just a very slow "ping" you can just send one batch rather than looping.

**Comment by matin-karimpour** [comment]
Thank you for your quick response :))
your answers really helped me :))
Can I have your email for upcoming questions?

**Comment by cliffburdick** [comment]
Hi @matin-karimpour, we typically respond directly on GH issues, so feel free to add issues and tag me so I can an alert. It's better to go that route so others can search and find similar issues.
