### ISSUE TITLE
github page url 404 https://nvidia-holoscan.github.io/holohub/

### ISSUE THREAD

**Issue by wyli** [nvidia-holoscan/holohub#539]
Hello! I've been reading the holohub documentation of holohub and came across the webpage of holohub doesn't seem to work
<img width="868" alt="Screenshot 2024-10-16 at 09 58 20" src="https://github.com/user-attachments/assets/5d4f05ae-06fa-42be-85e4-ed0d8b818d88">

**Comment by tbirdso** [comment]
Hey @wyli , thanks for checking out HoloHub!

We are in the process of moving away from the `nvidia-holoscan.github.io` landing page. Links to `nvidia-holoscan.github.io` should be updated to `github.com/nvidia-holoscan/holohub` for the time being.

Could you please share the documentation location where you found the broken link? If it was in HoloHub we can fix it, otherwise a workaround is not currently planned.

**Comment by wyli** [comment]
I see, I found it within this page https://docs.nvidia.com/holoscan/sdk-user-guide/overview.html search 'holohub'.

(a quick search shows urls mostly from holoscan sdk https://github.com/search?q=org%3Anvidia-holoscan%20%22nvidia-holoscan.github.io%22&type=code )

**Comment by tbirdso** [comment]
Thanks, we will fix those documentation links in our next Holoscan SDK monthly release or sooner. FYI @jjomier

**Comment by tbirdso** [comment]
Holoscan SDK v2.6.0 user guide references to HoloHub are fixed and now point to the HoloHub GitHub page: https://docs.nvidia.com/holoscan/sdk-user-guide/index.html

Obsolete HoloHub landing page reference is removed from the GitHub organization README: https://github.com/nvidia-holoscan
